### ISSUE TITLE
Collection asset 'users/ob285/hexes/aphex' not found

### ISSUE THREAD

**Issue by sgascoin** [OllyBartlett/Roland_And_Bartlett_et_al_2024#1]
Could you share the asset (aphex) to allow other users to run your code? 

https://github.com/OllyBartlett/Roland_And_Bartlett_et_al_2024/blob/217cb3ee9d5f1ac6e0b6d03679d352e5af4ff892/GAP_Code_C2_TOA#L7

**Comment by OllyBartlett** [comment]
Thanks for flagging, shared so anyone can read :)

**Comment by sgascoin** [comment]
Many thanks for sharing a clean code, it allowed me to revisit your analysis here https://labo.obs-mip.fr/multitemp/is-antarctica-greening/

**Comment by OllyBartlett** [comment]
Thanks Simon for sharing your interpretation of our results. I really enjoyed reading your take and follow-up on our work!
